"""Add Identity and Campaign Models

Revision ID: d0e496e6fd2d
Revises: 29241f033a4f
Create Date: 2026-09-07 18:07:24.644828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'd0e496e6fd2d'
down_revision: Union[str, None] = '29241f033a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_intelligence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('positive_keywords', sa.JSON(), nullable=False),
    sa.Column('negative_keywords', sa.JSON(), nullable=False),
    sa.Column('buying_intent_phrases', sa.JSON(), nullable=False),
    sa.Column('problem_phrases', sa.JSON(), nullable=False),
    sa.Column('semantic_queries', sa.JSON(), nullable=False),
    sa.Column('source_specific_queries', sa.JSON(), nullable=False),
    sa.Column('icp_rules', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_intelligence_campaign_id'), 'campaign_intelligence', ['campaign_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_description', sa.String(), nullable=False),
    sa.Column('target_industry', sa.String(), nullable=True),
    sa.Column('target_geography', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('target_personas', sa.JSON(), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('enriched_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_source'), 'crawl_runs', ['source'], unique=False)
    op.create_table('discovery_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signals_discovered', sa.Integer(), nullable=False),
    sa.Column('signals_processed', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_jobs_campaign_id'), 'discovery_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_discovery_jobs_status'), 'discovery_jobs', ['status'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_version', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error_information', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_external_id'), 'raw_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_events_processing_status'), 'raw_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_raw_events_source_name'), 'raw_events', ['source_name'], unique=False)
    op.create_table('raw_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_signals_external_id'), 'raw_signals', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_signals_published_at'), 'raw_signals', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_signals_source'), 'raw_signals', ['source'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('rate_limit_hits', sa.Integer(), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_source_name'), 'source_health', ['source_name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_signal_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('business_pain', sa.String(), nullable=True),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('detected_need', sa.String(), nullable=True),
    sa.Column('explicit_requirement', sa.Boolean(), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('iosys_service', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_country'), 'signals', ['country'], unique=False)
    op.create_index(op.f('ix_signals_industry'), 'signals', ['industry'], unique=False)
    op.create_index(op.f('ix_signals_intent_score'), 'signals', ['intent_score'], unique=False)
    op.create_index(op.f('ix_signals_published_at'), 'signals', ['published_at'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    op.create_index(op.f('ix_signals_source_signal_id'), 'signals', ['source_signal_id'], unique=False)
    op.create_index(op.f('ix_signals_technology'), 'signals', ['technology'], unique=False)
    op.create_table('unified_signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('author', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('raw_event_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedding', app.models.unified_signal.VectorFallback(), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_unified_signals_campaign_id'), 'unified_signals', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_unified_signals_content_hash'), 'unified_signals', ['content_hash'], unique=False)
    op.create_index(op.f('ix_unified_signals_external_id'), 'unified_signals', ['external_id'], unique=False)
    op.create_index(op.f('ix_unified_signals_published_at'), 'unified_signals', ['published_at'], unique=False)
    op.create_index(op.f('ix_unified_signals_raw_event_id'), 'unified_signals', ['raw_event_id'], unique=False)
    op.create_index(op.f('ix_unified_signals_source'), 'unified_signals', ['source'], unique=False)
    op.create_index(op.f('ix_unified_signals_source_type'), 'unified_signals', ['source_type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrichment_status', sa.String(), nullable=False),
    sa.Column('enrichment_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['unified_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_signal_id'), 'leads', ['signal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_signal_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_unified_signals_source_type'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_source'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_raw_event_id'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_published_at'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_external_id'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_content_hash'), table_name='unified_signals')
    op.drop_index(op.f('ix_unified_signals_campaign_id'), table_name='unified_signals')
    op.drop_table('unified_signals')
    op.drop_index(op.f('ix_signals_technology'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_signal_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_published_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_intent_score'), table_name='signals')
    op.drop_index(op.f('ix_signals_industry'), table_name='signals')
    op.drop_index(op.f('ix_signals_country'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_source_health_source_name'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_raw_signals_source'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_published_at'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_external_id'), table_name='raw_signals')
    op.drop_table('raw_signals')
    op.drop_index(op.f('ix_raw_events_source_name'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_processing_status'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_external_id'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_discovery_jobs_status'), table_name='discovery_jobs')
    op.drop_index(op.f('ix_discovery_jobs_campaign_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    op.drop_index(op.f('ix_crawl_runs_source'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_campaign_intelligence_campaign_id'), table_name='campaign_intelligence')
    op.drop_table('campaign_intelligence')
    # ### end Alembic commands ###
